name: 'LeanIX Storage Deployment'
description: 'Deploy files to blob storage'
inputs:
  container:
    description: 'Name of the storage container to deploy to'
    required: true
  source-directory:
    description: 'Directory containing the files to deploy'
    default: '.'
    required: true
  environment:
    description: 'Environment to deploy to'
    default: 'test'
    required: false
  region:
    description: 'Region to deploy to'
    default: ''
    required: false
  delete-destination:
    description: 'Delete files on destination if they no longer exist in the source'
    default: 'true'
    required: false
  version-deployment:
    description: 'Whether to version the deployment'
    default: 'false'
    required: false
  branch-name:
    description: 'Name of the branch for which you want to version a deployment'
    default: ''
    required: false
  app-name:
    description: 'Name of the app for which you want to version a deployment'
    default: ''
    required: false
outputs:
  version:
    description: 'The deployed version number'
runs:
  using: 'node12'
  main: 'dist/index.js'