name: 'LeanIX Storage Deployment'
description: 'Deploy files to blob storage'
inputs:
  container:
    description: 'Name of the storage container to deploy to'
    required: true
  source-directory:
    description: 'Directory containing the files to deploy'
    default: ''
    required: false 
  environment:
    description: 'Environment to deploy to'
    default: 'test'
    required: false
  region:
    description: 'Region to deploy to'
    default: ''
    required: false
  delete-destination:
    description: 'Delete files on destination if they no longer exist in the source'
    default: 'true'
    required: false
  branch:
    description: 'Name of the branch that you want to deploy'
    default: ''
    required: false 
  microfrontend:
    description: 'Name of microfrontend if a microfrontend from a monorepo is supposed to be deployed'
    default: ''
    required: false
  rollback-mode:
    description: 'Activate the rollback mode. If activated rolls back any index.html and main.js on the given container to the given version'
    default: 'false'
    required: false
  rollback-version:
    description: 'The version to rollback to, if in rollback mode'
    default: ''
    required: false
outputs:
  version:
    description: 'The deployed version'
runs:
  using: 'node12'
  main: 'dist/index.js'