name: 'LeanIX Storage Deployment'
description: 'Deploy files to blob storage'
inputs:
  branch:
    description: 'Name of the branch that you want to deploy'
    required: true
  container:
    description: 'Name of the storage container to deploy to'
    required: true
  source-directory:
    description: 'Directory containing the files to deploy'
    default: '.'
    required: true
  environment:
    description: 'Environment to deploy to'
    default: 'test'
    required: false
  region:
    description: 'Region to deploy to'
    default: ''
    required: false
  delete-destination:
    description: 'Delete files on destination if they no longer exist in the source'
    default: 'true'
    required: false
  microfrontend:
    description: 'Name of microfrontend if a microfrontend from a monorepo is supposed to be deployed'
    default: ''
    required: false
outputs:
  version:
    description: 'The deployed version'
runs:
  using: 'node12'
  main: 'dist/index.js'