name: Test storage deploy
on: [push]

jobs:
  test:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}
      
      - name: Fetch SAS token to access leanixwesteuropetest Azure File Storage
        run: sh ./.github/workflows/fetch_sas_token.sh
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
      
      - name: Define constants 
        run: sh ./.github/workflows/define_test_constants.sh
        env:
          SAS_TOKEN: ${{ env.SAS_TOKEN }}

      - name: Use storage deploy action
        uses: ./
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: test

      - name: Use storage deploy action with region option
        uses: ./
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: westeurope
      
      - name: Deployment to Azure Blob Storage has been successful
        run: sh ./.github/workflows/validate_azure_blob_deployment.sh
      
      - name: Deployment to Azure File Share has been successful
        run: sh ./.github/workflows/validate_azure_file_share_deployment.sh
      
      - name: Use storage deploy action with versioning
        uses: ./
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: westeurope
          version-deployment: true
          app-name: test-microfrontend
        id: versioned-deployment
      
      - name: Versioned deployment to Azure Blob storage has been successful
        run: sh ./.github/workflows/validate_versioned_azure_blob_deployment.sh
        env:
          VERSION: ${{ steps.versioned-deployment.outputs.version }}

      - name: Versioned deployment to Azure File Share has been successful
        run: sh ./.github/workflows/validate_versioned_azure_file_share_deployment.sh
        env:
          SAS_TOKEN: ${{ env.SAS_TOKEN }}
          VERSION: ${{ steps.versioned-deployment.outputs.version }}
      
      - name: Introduce breaking change
        run: python ./.github/workflows/make_breaking_change.py
      
      - name: Deploy a breaking change without versioning
        uses: ./
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: westeurope
          delete-destination: false

      - name: Deployment of breaking change to Azure Blob storage successful
        run: sh ./.github/workflows/validate_breaking_azure_blob_deployment.sh
      
      - name: Deployment of breaking change to Azure File Share successful
        run: sh ./.github/workflows/validate_breaking_azure_file_share_deployment.sh

      
      - name: Rollback breaking change
        uses: ./
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: westeurope
          in-rollback-mode: true
          rollback-version: ${{ steps.versioned-deployment.outputs.version }}
      
      - name: Rollback on Azure Blob storage successful
        run: sh ./.github/workflows/validate_rollback_on_azure_blob.sh
      
      - name: Rollback on Azure File Share successful
        run: sh ./.github/workflows/validate_rollback_on_azure_file_share.sh

      - name: Should fail because of unsupported region
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: northeurope

      - name: Should fail because of forbidden container name
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: foobar

      - name: Should fail because of not existing container name
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: storage-deploy-action-unknown

      - name: Should fail because of invalid region
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: storage-deploy-action-public
          region: foobar

      - name: Should fail because of invalid environment
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: foobar

      - name: Rollback fails, if no rollback-version specified
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          in-rollback-mode: true
