name: Test storage deploy
on: [push]

jobs:
  test:
    name: Test Deployment and Rollback
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch
      
      - name: Deploy a microfrontend to all regions
        uses: ./
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          microfrontend: test-microfrontend

      - name: Deploy a microfrontend with region option
        uses: ./
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: westeurope
          microfrontend: test-microfrontend
        id: initial-deployment 

      - name: Deployment has been successful index.html and main.js
        shell: bash
        run: |
          expected="<h1>Hello World!</h1>console.log('Hello World!');"
          received=$(curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index.html && curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main.js)
          echo "received: " $received
          if [[ $received != *"$expected"* ]]; then
            echo "::error ::Deployment has not been successful"
            exit 1
          fi

      - name: Modify the microfrontend by introducing a breaking change
        run: python ./.github/workflows/introduce_breaking_change.py

      - name: Deploy breaking change without versioning 
        uses: ./
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: westeurope
          microfrontend: test-microfronted
          version-deployment: false
        id: breaking-change-deployment

      - name: Deployment of breaking change has been successful 
        shell: bash
        run: |
          expected="<h1>Breaking Change</h1>console.log('Breaking Change');"
          received=$(curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index.html && curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main.js)
          echo "received: " $received
          if [[ $received != *"$expected"* ]]; then
            echo "::error ::Deployment has not been successful"
            exit 1
          fi

      - name: Rollback the breaking change deployment to the initial deployed version
        uses: ./
        with:
          container: storage-deploy-action-public
          source-directory: test
          environment: test
          region: westeurope
          rollback-mode: true
          rollback-version: ${{ steps.initial-deployment.outputs.version }}

      - name: Rollback of index.html and main.js has been successful
        shell: bash
        run: |
          expected="<h1>Hello World!</h1>console.log('Hello World!');"
          received=$(curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index.html && curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main.js)
          echo "received: " $received
          if [[ $received != *"$expected"* ]]; then
            echo "::error ::Rollback has not been successful"
            exit 1
          fi

      - name: Rollback fails, if no rollback-version specified
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          rollback-mode: true
      
      - name: Fails because of unsupported region
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: northeurope
      
      - name: Fails because of forbidden container name
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: foobar

      - name: Fails because of non-existing container name
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-unknown

      - name: Fails because of invalid region
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          region: foobar

      - name: Fails because of invalid environment
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: foobar

      - name: Fails because no branch provided
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: storage-deploy-action-public
