name: Test storage deploy
on: [push]

jobs:
  test:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch

      - name: Use storage deploy action
        uses: ./
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
      
      - name: Use storage deploy action for deploying a microfrontend
        uses: ./
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          microfrontend: test-microfrontend

      - name: Use storage deploy action with region option
        uses: ./
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: westeurope

      - name: Should fail because of unsupported region
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: test
          region: northeurope

      - name: Should fail because of forbidden container name
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: foobar

      - name: Should fail because of not existing container name
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-unknown

      - name: Should fail because of invalid region
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          region: foobar

      - name: Should fail because of invalid environment
        uses: ./
        continue-on-error: true
        with:
          branch: ${{ steps.extract-branch.outputs.branch }}
          source-directory: test
          container: storage-deploy-action-public
          environment: foobar
      
      - name: Should fail because no branch provided
        uses: ./
        continue-on-error: true
        with:
          source-directory: test
          container: storage-deploy-action-public